name: cocktail_flutter_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  flutter_staggered_grid_view: ^0.6.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  
 


flutter:

  uses-material-design: true

 